/*
 * Package main ORY Keto
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type ConsentRequestRejection struct {

	// Reason represents the reason why the user rejected the consent request.
	Reason string `json:"reason,omitempty"`
}
