/*
 * Package main ORY Keto
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// Group represents a warden group
type Group struct {

	// ID is the groups id.
	Id string `json:"id,omitempty"`

	// Members is who belongs to the group.
	Members []string `json:"members,omitempty"`
}
