/*
 * Package main ORY Keto
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Handler struct {
	Generators map[string]KeyGenerator `json:"Generators,omitempty"`

	H Writer `json:"H,omitempty"`

	Manager Manager `json:"Manager,omitempty"`

	ResourcePrefix string `json:"ResourcePrefix,omitempty"`

	W Firewall `json:"W,omitempty"`
}
