/*
 * Package main ORY Keto
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type JoseWebKeySetRequest struct {
	Keys []RawMessage `json:"keys,omitempty"`
}
