/*
 * Package main ORY Keto
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type OAuth2ConsentRequest struct {

	// ClientID is the client id that initiated the OAuth2 request.
	ClientId string `json:"clientId,omitempty"`

	// ExpiresAt is the time where the access request will expire.
	ExpiresAt string `json:"expiresAt,omitempty"`

	// ID is the id of this consent request.
	Id string `json:"id,omitempty"`

	// Redirect URL is the URL where the user agent should be redirected to after the consent has been accepted or rejected.
	RedirectUrl string `json:"redirectUrl,omitempty"`

	// RequestedScopes represents a list of scopes that have been requested by the OAuth2 request initiator.
	RequestedScopes []string `json:"requestedScopes,omitempty"`
}
