/*
 * Package main ORY Keto
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// It implements Marshaler and Unmarshaler and can be used to delay JSON decoding or precompute a JSON encoding.
type RawMessage struct {
}
