/*
 * Package main ORY Keto
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type SwaggerDoesWardenAllowTokenAccessRequestParameters struct {
	Body WardenTokenAccessRequest `json:"Body,omitempty"`
}
