/*
 * Package main ORY Keto
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type SwaggerRejectConsentRequest struct {
	Body ConsentRequestRejection `json:"Body"`

	// in: path
	Id string `json:"id"`
}
