/*
 * Package main ORY Keto
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// The token introspection response
type SwaggerOAuthIntrospectionResponse struct {
	Body OAuth2TokenIntrospection `json:"Body,omitempty"`
}
