/*
 * Package main ORY Keto
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type SwaggerOAuthConsentRequestPayload struct {

	// The id of the OAuth 2.0 Consent Request.
	Id string `json:"id"`
}
