<?php
/**
 * JsonWebKeyApiTest
 * PHP version 5
 *
 * @category Class
 * @package  keto\SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Package main ORY Keto
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace keto\SDK;

use \keto\SDK\Configuration;
use \keto\SDK\ApiClient;
use \keto\SDK\ApiException;
use \keto\SDK\ObjectSerializer;

/**
 * JsonWebKeyApiTest Class Doc Comment
 *
 * @category Class
 * @package  keto\SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class JsonWebKeyApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createJsonWebKeySet
     *
     * Generate a new JSON Web Key.
     *
     */
    public function testCreateJsonWebKeySet()
    {
    }

    /**
     * Test case for deleteJsonWebKey
     *
     * Delete a JSON Web Key.
     *
     */
    public function testDeleteJsonWebKey()
    {
    }

    /**
     * Test case for deleteJsonWebKeySet
     *
     * Delete a JSON Web Key.
     *
     */
    public function testDeleteJsonWebKeySet()
    {
    }

    /**
     * Test case for getJsonWebKey
     *
     * Retrieve a JSON Web Key.
     *
     */
    public function testGetJsonWebKey()
    {
    }

    /**
     * Test case for getJsonWebKeySet
     *
     * Retrieve a JSON Web Key Set.
     *
     */
    public function testGetJsonWebKeySet()
    {
    }

    /**
     * Test case for updateJsonWebKey
     *
     * Update a JSON Web Key.
     *
     */
    public function testUpdateJsonWebKey()
    {
    }

    /**
     * Test case for updateJsonWebKeySet
     *
     * Update a JSON Web Key Set.
     *
     */
    public function testUpdateJsonWebKeySet()
    {
    }
}
