<?php
/**
 * OAuth2ApiTest
 * PHP version 5
 *
 * @category Class
 * @package  keto\SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Package main ORY Keto
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace keto\SDK;

use \keto\SDK\Configuration;
use \keto\SDK\ApiClient;
use \keto\SDK\ApiException;
use \keto\SDK\ObjectSerializer;

/**
 * OAuth2ApiTest Class Doc Comment
 *
 * @category Class
 * @package  keto\SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OAuth2ApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for acceptOAuth2ConsentRequest
     *
     * Accept a consent request.
     *
     */
    public function testAcceptOAuth2ConsentRequest()
    {
    }

    /**
     * Test case for createOAuth2Client
     *
     * Create an OAuth 2.0 client.
     *
     */
    public function testCreateOAuth2Client()
    {
    }

    /**
     * Test case for deleteOAuth2Client
     *
     * Deletes an OAuth 2.0 Client.
     *
     */
    public function testDeleteOAuth2Client()
    {
    }

    /**
     * Test case for getOAuth2Client
     *
     * Retrieve an OAuth 2.0 Client..
     *
     */
    public function testGetOAuth2Client()
    {
    }

    /**
     * Test case for getOAuth2ConsentRequest
     *
     * Receive consent request information.
     *
     */
    public function testGetOAuth2ConsentRequest()
    {
    }

    /**
     * Test case for getWellKnown
     *
     * Server well known configuration.
     *
     */
    public function testGetWellKnown()
    {
    }

    /**
     * Test case for introspectOAuth2Token
     *
     * Introspect OAuth2 tokens.
     *
     */
    public function testIntrospectOAuth2Token()
    {
    }

    /**
     * Test case for listOAuth2Clients
     *
     * List OAuth 2.0 Clients.
     *
     */
    public function testListOAuth2Clients()
    {
    }

    /**
     * Test case for oauthAuth
     *
     * The OAuth 2.0 authorize endpoint.
     *
     */
    public function testOauthAuth()
    {
    }

    /**
     * Test case for oauthToken
     *
     * The OAuth 2.0 token endpoint.
     *
     */
    public function testOauthToken()
    {
    }

    /**
     * Test case for rejectOAuth2ConsentRequest
     *
     * Reject a consent request.
     *
     */
    public function testRejectOAuth2ConsentRequest()
    {
    }

    /**
     * Test case for revokeOAuth2Token
     *
     * Revoke OAuth2 tokens.
     *
     */
    public function testRevokeOAuth2Token()
    {
    }

    /**
     * Test case for updateOAuth2Client
     *
     * Update an OAuth 2.0 Client.
     *
     */
    public function testUpdateOAuth2Client()
    {
    }

    /**
     * Test case for userinfo
     *
     * OpenID Connect Userinfo.
     *
     */
    public function testUserinfo()
    {
    }

    /**
     * Test case for wellKnown
     *
     * Get list of well known JSON Web Keys.
     *
     */
    public function testWellKnown()
    {
    }
}
