<?php
/**
 * PolicyApiTest
 * PHP version 5
 *
 * @category Class
 * @package  keto\SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Package main ORY Keto
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace keto\SDK;

use \keto\SDK\Configuration;
use \keto\SDK\ApiClient;
use \keto\SDK\ApiException;
use \keto\SDK\ObjectSerializer;

/**
 * PolicyApiTest Class Doc Comment
 *
 * @category Class
 * @package  keto\SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PolicyApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createPolicy
     *
     * Create an Access Control Policy.
     *
     */
    public function testCreatePolicy()
    {
    }

    /**
     * Test case for deletePolicy
     *
     * Delete an Access Control Policy.
     *
     */
    public function testDeletePolicy()
    {
    }

    /**
     * Test case for getPolicy
     *
     * Get an Access Control Policy.
     *
     */
    public function testGetPolicy()
    {
    }

    /**
     * Test case for listPolicies
     *
     * List Access Control Policies.
     *
     */
    public function testListPolicies()
    {
    }

    /**
     * Test case for updatePolicy
     *
     * Update an Access Control Polic.
     *
     */
    public function testUpdatePolicy()
    {
    }
}
