<?php
/**
 * WardenApiTest
 * PHP version 5
 *
 * @category Class
 * @package  keto\SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Package main ORY Keto
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace keto\SDK;

use \keto\SDK\Configuration;
use \keto\SDK\ApiClient;
use \keto\SDK\ApiException;
use \keto\SDK\ObjectSerializer;

/**
 * WardenApiTest Class Doc Comment
 *
 * @category Class
 * @package  keto\SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class WardenApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addMembersToGroup
     *
     * Add members to a group.
     *
     */
    public function testAddMembersToGroup()
    {
    }

    /**
     * Test case for createGroup
     *
     * Create a group.
     *
     */
    public function testCreateGroup()
    {
    }

    /**
     * Test case for deleteGroup
     *
     * Delete a group by id.
     *
     */
    public function testDeleteGroup()
    {
    }

    /**
     * Test case for doesWardenAllowAccessRequest
     *
     * Check if an access request is valid (without providing an access token).
     *
     */
    public function testDoesWardenAllowAccessRequest()
    {
    }

    /**
     * Test case for doesWardenAllowTokenAccessRequest
     *
     * Check if an access request is valid (providing an access token).
     *
     */
    public function testDoesWardenAllowTokenAccessRequest()
    {
    }

    /**
     * Test case for getGroup
     *
     * Get a group by id.
     *
     */
    public function testGetGroup()
    {
    }

    /**
     * Test case for listGroups
     *
     * List groups.
     *
     */
    public function testListGroups()
    {
    }

    /**
     * Test case for removeMembersFromGroup
     *
     * Remove members from a group.
     *
     */
    public function testRemoveMembersFromGroup()
    {
    }
}
