<?php
/**
 * ConsentRequestAcceptanceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  keto\SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Package main ORY Keto
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace keto\SDK;

/**
 * ConsentRequestAcceptanceTest Class Doc Comment
 *
 * @category    Class */
// * @description ConsentRequestAcceptance
/**
 * @package     keto\SDK
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ConsentRequestAcceptanceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ConsentRequestAcceptance"
     */
    public function testConsentRequestAcceptance()
    {
    }

    /**
     * Test attribute "access_token_extra"
     */
    public function testPropertyAccessTokenExtra()
    {
    }

    /**
     * Test attribute "grant_scopes"
     */
    public function testPropertyGrantScopes()
    {
    }

    /**
     * Test attribute "id_token_extra"
     */
    public function testPropertyIdTokenExtra()
    {
    }

    /**
     * Test attribute "subject"
     */
    public function testPropertySubject()
    {
    }
}
