<?php
/**
 * HandlerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  keto\SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Package main ORY Keto
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace keto\SDK;

/**
 * HandlerTest Class Doc Comment
 *
 * @category    Class */
// * @description Handler
/**
 * @package     keto\SDK
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HandlerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Handler"
     */
    public function testHandler()
    {
    }

    /**
     * Test attribute "generators"
     */
    public function testPropertyGenerators()
    {
    }

    /**
     * Test attribute "h"
     */
    public function testPropertyH()
    {
    }

    /**
     * Test attribute "manager"
     */
    public function testPropertyManager()
    {
    }

    /**
     * Test attribute "resource_prefix"
     */
    public function testPropertyResourcePrefix()
    {
    }

    /**
     * Test attribute "w"
     */
    public function testPropertyW()
    {
    }
}
