<?php
/**
 * JsonWebKeyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  keto\SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Package main ORY Keto
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace keto\SDK;

/**
 * JsonWebKeyTest Class Doc Comment
 *
 * @category    Class */
// * @description JsonWebKey
/**
 * @package     keto\SDK
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class JsonWebKeyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "JsonWebKey"
     */
    public function testJsonWebKey()
    {
    }

    /**
     * Test attribute "alg"
     */
    public function testPropertyAlg()
    {
    }

    /**
     * Test attribute "crv"
     */
    public function testPropertyCrv()
    {
    }

    /**
     * Test attribute "d"
     */
    public function testPropertyD()
    {
    }

    /**
     * Test attribute "dp"
     */
    public function testPropertyDp()
    {
    }

    /**
     * Test attribute "dq"
     */
    public function testPropertyDq()
    {
    }

    /**
     * Test attribute "e"
     */
    public function testPropertyE()
    {
    }

    /**
     * Test attribute "k"
     */
    public function testPropertyK()
    {
    }

    /**
     * Test attribute "kid"
     */
    public function testPropertyKid()
    {
    }

    /**
     * Test attribute "kty"
     */
    public function testPropertyKty()
    {
    }

    /**
     * Test attribute "n"
     */
    public function testPropertyN()
    {
    }

    /**
     * Test attribute "p"
     */
    public function testPropertyP()
    {
    }

    /**
     * Test attribute "q"
     */
    public function testPropertyQ()
    {
    }

    /**
     * Test attribute "qi"
     */
    public function testPropertyQi()
    {
    }

    /**
     * Test attribute "use"
     */
    public function testPropertyUse()
    {
    }

    /**
     * Test attribute "x"
     */
    public function testPropertyX()
    {
    }

    /**
     * Test attribute "x5c"
     */
    public function testPropertyX5c()
    {
    }

    /**
     * Test attribute "y"
     */
    public function testPropertyY()
    {
    }
}
