<?php
/**
 * OAuth2ClientTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  keto\SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Package main ORY Keto
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace keto\SDK;

/**
 * OAuth2ClientTest Class Doc Comment
 *
 * @category    Class */
// * @description OAuth2Client
/**
 * @package     keto\SDK
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OAuth2ClientTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OAuth2Client"
     */
    public function testOAuth2Client()
    {
    }

    /**
     * Test attribute "client_name"
     */
    public function testPropertyClientName()
    {
    }

    /**
     * Test attribute "client_secret"
     */
    public function testPropertyClientSecret()
    {
    }

    /**
     * Test attribute "client_uri"
     */
    public function testPropertyClientUri()
    {
    }

    /**
     * Test attribute "contacts"
     */
    public function testPropertyContacts()
    {
    }

    /**
     * Test attribute "grant_types"
     */
    public function testPropertyGrantTypes()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "logo_uri"
     */
    public function testPropertyLogoUri()
    {
    }

    /**
     * Test attribute "owner"
     */
    public function testPropertyOwner()
    {
    }

    /**
     * Test attribute "policy_uri"
     */
    public function testPropertyPolicyUri()
    {
    }

    /**
     * Test attribute "public"
     */
    public function testPropertyPublic()
    {
    }

    /**
     * Test attribute "redirect_uris"
     */
    public function testPropertyRedirectUris()
    {
    }

    /**
     * Test attribute "response_types"
     */
    public function testPropertyResponseTypes()
    {
    }

    /**
     * Test attribute "scope"
     */
    public function testPropertyScope()
    {
    }

    /**
     * Test attribute "tos_uri"
     */
    public function testPropertyTosUri()
    {
    }
}
