<?php
/**
 * OAuth2TokenIntrospectionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  keto\SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Package main ORY Keto
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace keto\SDK;

/**
 * OAuth2TokenIntrospectionTest Class Doc Comment
 *
 * @category    Class */
// * @description OAuth2TokenIntrospection
/**
 * @package     keto\SDK
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OAuth2TokenIntrospectionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OAuth2TokenIntrospection"
     */
    public function testOAuth2TokenIntrospection()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "aud"
     */
    public function testPropertyAud()
    {
    }

    /**
     * Test attribute "client_id"
     */
    public function testPropertyClientId()
    {
    }

    /**
     * Test attribute "exp"
     */
    public function testPropertyExp()
    {
    }

    /**
     * Test attribute "ext"
     */
    public function testPropertyExt()
    {
    }

    /**
     * Test attribute "iat"
     */
    public function testPropertyIat()
    {
    }

    /**
     * Test attribute "iss"
     */
    public function testPropertyIss()
    {
    }

    /**
     * Test attribute "nbf"
     */
    public function testPropertyNbf()
    {
    }

    /**
     * Test attribute "scope"
     */
    public function testPropertyScope()
    {
    }

    /**
     * Test attribute "sub"
     */
    public function testPropertySub()
    {
    }

    /**
     * Test attribute "username"
     */
    public function testPropertyUsername()
    {
    }
}
