<?php
/**
 * WellKnownTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  keto\SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Package main ORY Keto
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace keto\SDK;

/**
 * WellKnownTest Class Doc Comment
 *
 * @category    Class */
// * @description WellKnown
/**
 * @package     keto\SDK
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WellKnownTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "WellKnown"
     */
    public function testWellKnown()
    {
    }

    /**
     * Test attribute "authorization_endpoint"
     */
    public function testPropertyAuthorizationEndpoint()
    {
    }

    /**
     * Test attribute "claims_supported"
     */
    public function testPropertyClaimsSupported()
    {
    }

    /**
     * Test attribute "id_token_signing_alg_values_supported"
     */
    public function testPropertyIdTokenSigningAlgValuesSupported()
    {
    }

    /**
     * Test attribute "issuer"
     */
    public function testPropertyIssuer()
    {
    }

    /**
     * Test attribute "jwks_uri"
     */
    public function testPropertyJwksUri()
    {
    }

    /**
     * Test attribute "response_types_supported"
     */
    public function testPropertyResponseTypesSupported()
    {
    }

    /**
     * Test attribute "scopes_supported"
     */
    public function testPropertyScopesSupported()
    {
    }

    /**
     * Test attribute "subject_types_supported"
     */
    public function testPropertySubjectTypesSupported()
    {
    }

    /**
     * Test attribute "token_endpoint"
     */
    public function testPropertyTokenEndpoint()
    {
    }

    /**
     * Test attribute "token_endpoint_auth_methods_supported"
     */
    public function testPropertyTokenEndpointAuthMethodsSupported()
    {
    }

    /**
     * Test attribute "userinfo_endpoint"
     */
    public function testPropertyUserinfoEndpoint()
    {
    }
}
