/**
 * 
 * Package main ORY Keto
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/WardenAccessRequestResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./WardenAccessRequestResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.SwaggerJsClient) {
      root.SwaggerJsClient = {};
    }
    root.SwaggerJsClient.SwaggerWardenAccessRequestResponseParameters = factory(root.SwaggerJsClient.ApiClient, root.SwaggerJsClient.WardenAccessRequestResponse);
  }
}(this, function(ApiClient, WardenAccessRequestResponse) {
  'use strict';




  /**
   * The SwaggerWardenAccessRequestResponseParameters model module.
   * @module model/SwaggerWardenAccessRequestResponseParameters
   * @version Latest
   */

  /**
   * Constructs a new <code>SwaggerWardenAccessRequestResponseParameters</code>.
   * The warden access request response
   * @alias module:model/SwaggerWardenAccessRequestResponseParameters
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>SwaggerWardenAccessRequestResponseParameters</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SwaggerWardenAccessRequestResponseParameters} obj Optional instance to populate.
   * @return {module:model/SwaggerWardenAccessRequestResponseParameters} The populated <code>SwaggerWardenAccessRequestResponseParameters</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Body')) {
        obj['Body'] = WardenAccessRequestResponse.constructFromObject(data['Body']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/WardenAccessRequestResponse} Body
   */
  exports.prototype['Body'] = undefined;



  return exports;
}));


