/*
 * Package main ORY Hades
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type SwaggerDoesWardenAllowTokenAccessRqeuestParameters struct {
	Body IsOAuth2AccessTokenAuthorized `json:"Body,omitempty"`
}
